services:
  pre-filing-api:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pre-filing.entrypoints=websecure"
      - "traefik.http.routers.pre-filing.rule=Host(`${APP_HOST}`) && PathPrefix(`/v1/paper-books`)"
      - "traefik.http.routers.pre-filing.tls=true"
      - "traefik.http.routers.pre-filing.tls.certresolver=myresolver"
      - "traefik.http.routers.pre-filing.middlewares=pre-filing-strip"
      - "traefik.http.middlewares.pre-filing-strip.stripprefix.prefixes=/v1/paper-books"
    networks:
      - shared-network

networks:
  shared-network:
    external: true
